CREATE TABLE teams_formation (
   id SERIAL,
   name varchar(255),
   formation formation,
   owner integer,
   GK integer,
   LS integer, 
   ST integer, 
   RS integer, 
   LW integer, 
   LF integer,
   CF integer,
   RF integer, 
   RW integer, 
   LAM integer, 
   CAM integer, 
   RAM integer, 
   LM integer, 
   LCM integer, 
   CM integer, 
   RCM integer, 
   RM integer, 
   LWB integer, 
   LDM integer, 
   CDM integer, 
   RDM integer, 
   RWB integer, 
   LB integer, 
   LCB integer, 
   CB integer, 
   RCB integer, 
   RB integer,
   foreign key (owner) REFERENCES users (id)
);
